services:
  db:
    image: postgres:17
    container_name: tasksync-postgres
    restart: always
    environment:
      POSTGRES_DB: tasksyncdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db-init:/docker-entrypoint-initdb.d
    networks:
      - tasksync-net

  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    ports:
      - "50051:50051"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: tasksyncdb
    depends_on:
      - db
    networks:
      - tasksync-net
    # volumes:
      # - .:/app
    working_dir: /app
    entrypoint: ["sh", "cmd/server/wait-for-db.sh"]

  client:
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    depends_on:
      - server
    networks:
      - tasksync-net
    # volumes:
      # - .:/app
    working_dir: /app
    entrypoint: ["sh", "cmd/client/wait-for-server.sh"]

volumes:
  pgdata:

networks:
  tasksync-net:
