version: '3.8'

services:
  db:
    image: postgres:17
    container_name: tasksync-db
    restart: always
    environment:
      POSTGRES_DB: tasksync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tasksync-net
    
    server:
      build:
        context: .
        dockerfile: docker/Dockerfile.server
      ports:
        - "50051:50051"
      environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: 1234
        DB_NAME: tasksync
      depends_on:
        - db
      networks:
        - tasksync-net

  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    depends_on:
      - server
    networks:
      - tasksync-net
  
  volumes:
  pgdata:

  networks:
    tasksync-net:
  # server:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.server
  #   ports:
  #     - "50051:50051"

  # client:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.client
  #   depends_on:
  #     - server

# services:
#   db:
#     image: postgres:15
#     container_name: tasksync-db
#     restart: always
#     environment:
#       POSTGRES_DB: tasksync
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     networks:
#       - tasksync-net

#   server:
#     build:
#       context: .
#       dockerfile: docker/Dockerfile.server
#     ports:
#       - "50051:50051"
#     environment:
#       DB_HOST: db
#       DB_PORT: 5432
#       DB_USER: postgres
#       DB_PASSWORD: 1234
#       DB_NAME: tasksync
#     depends_on:
#       - db
#     networks:
#       - tasksync-net

#   client:
#     build:
#       context: .
#       dockerfile: docker/Dockerfile.client
#     depends_on:
#       - server
#     networks:
#       - tasksync-net

# volumes:
#   pgdata:

# networks:
#   tasksync-net:
